baseurl: 'https://davidfan.io' # Must point to GitHub, not custom domain
title: David Fan
DefaultContentLanguage: en
paginate: 20
pygmentsstyle: b2 # Color-theme or style for syntax highlighting.
pygmentscodefences: true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax: true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses: true # new add
publishDir: "docs"
permalinks:
  blog: /blog/:year/:month/:title/
googleAnalytics: 'UA-67735838-1'

params:
  author: David Fan
  description: David Fan's personal website
  keywords: >-
    David,Fan,Princeton,University,Amazon,Harvard-MIT HST,HackPrinceton,Science
    Olympiad,Computer Vision,Deep Learning,Machine Learning,Software
    Engineering, Bioinformatics,Research
  info: Applied Scientist at Amazon #Research Engineer at Amazon #Software Engineer at AWS AI # CS Student at Princeton
  avatarurl: images/david_hangzhou_2.jpg
  footercontent:
  fixedbarContent: # for footer
  fixedbarContentAfter: # for footer
  snsShare: false # enable social media icons on bottom footer
  thumbnail: images/thumbnails/home.png # default sns thumbnail
  itemscentered: true
  rtl: false
  langseparator: '|'
  social:
    - name: Google Scholar
      weight: 1
      url: 'https://scholar.google.com/citations?user=VAiqiv4AAAAJ&hl'
      icon: "fab fa-google fa-2x"
    - name: LinkedIn
      weight: 3
      url: 'https://linkedin.com/in/davidfan97/'
      icon: "fab fa-linkedin-in fa-2x"
    # - name: Github
    #   weight: 1
    #   url: 'https://github.com/dfan/'
    #   icon: "fab fa-github fa-2x"
    - name: Email
      weight: 4
      url: 'mailto:dfan@davidfan.io'
      icon: "fas fa-envelope fa-2x"
menu:
  main:
    - name: About
      weight: 1
      url: about
    - name: Experience
      weight: 2
      url: experience
    - name: Projects
      weight: 3
      url: projects
    - name: Publications
      weight: 4
      url: publications
    - name: Blog
      weight: 5
      url: blog
